import { Lesson } from "./exercises";

// Speech text preserves the visible romanized choices while giving Japanese
// voices native-script input. Particles use their spoken reading in isolation.
const JAPANESE_SPEECH: Record<string, string> = {
  mizu: "みず", pan: "パン", hito: "ひと", onna: "おんな",
  watashi: "わたし", wa: "わ", o: "お", tabemasu: "たべます",
  "onna no hito": "おんなのひと", "otoko no hito": "おとこのひと",
  kodomo: "こども", otoko: "おとこ", no: "の", nomimasu: "のみます",
  "otoko no ko": "おとこのこ", "onna no ko": "おんなのこ", ko: "こ",
  gyuunyuu: "ぎゅうにゅう", ogenki: "おげんき", desu: "です", ka: "か",
  hai: "はい", sayounara: "さようなら", haha: "はは", chichi: "ちち",
  ani: "あに", ane: "あね", musuko: "むすこ", musume: "むすめ",
  koko: "ここ", ni: "に", imasu: "います", otouto: "おとうと",
  san: "さん", yon: "よん", ichi: "いち", juu: "じゅう", go: "ご",
  nana: "なな", kyuu: "きゅう", hon: "ほん", nisatsu: "にさつ",
  motte: "もって", issatsu: "いっさつ",
};

// Each language has a 5-lesson path. Lessons unlock in order — see
// getUnlockedIndex in lib/progress.ts for the completion-gated unlock rule.
export const LESSON_PATHS: Record<string, Lesson[]> = {
  es: [
    {
      id: "es-basics-1",
      title: "Basics 1",
      exercises: [
        {
          id: "es-1-1",
          speech: { lang: "es-ES" },
          type: "multipleChoice",
          prompt: "Which word means \"the man\"?",
          options: ["el hombre", "la mujer", "el niño", "la niña"],
          answer: "el hombre",
        },
        {
          id: "es-1-2",
          speech: { lang: "es-ES" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "The woman drinks water",
          wordBank: ["La", "mujer", "bebe", "agua", "el", "pan"],
          answer: ["La", "mujer", "bebe", "agua"],
        },
        {
          id: "es-1-3",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Gracias\" means?",
          options: ["Thank you", "Please", "Sorry", "Hello"],
          answer: "Thank you",
        },
        {
          id: "es-1-4",
          speech: { lang: "es-ES" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "I eat bread",
          wordBank: ["Yo", "como", "pan", "tú", "comes", "agua"],
          answer: ["Yo", "como", "pan"],
        },
        {
          id: "es-1-5",
          speech: { lang: "es-ES" },
          type: "multipleChoice",
          prompt: "Which one means \"water\"?",
          options: ["pan", "agua", "leche", "mujer"],
          answer: "agua",
        },
      ],
    },
    {
      id: "es-basics-2",
      title: "Basics 2",
      exercises: [
        {
          id: "es-2-1",
          speech: { lang: "es-ES" },
          type: "multipleChoice",
          prompt: "Which word means \"the boy\"?",
          options: ["el niño", "la niña", "el hombre", "la mujer"],
          answer: "el niño",
        },
        {
          id: "es-2-2",
          speech: { lang: "es-ES" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "The girl eats bread",
          wordBank: ["La", "niña", "come", "pan", "el", "agua"],
          answer: ["La", "niña", "come", "pan"],
        },
        {
          id: "es-2-3",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Por favor\" means?",
          options: ["Please", "Thank you", "Sorry", "Hello"],
          answer: "Please",
        },
        {
          id: "es-2-4",
          speech: { lang: "es-ES" },
          type: "multipleChoice",
          prompt: "Which one means \"milk\"?",
          options: ["leche", "agua", "pan", "niño"],
          answer: "leche",
        },
      ],
    },
    {
      id: "es-basics-3",
      title: "Phrases",
      exercises: [
        {
          id: "es-3-1",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Buenos días\" means?",
          options: ["Good morning", "Good night", "Goodbye", "See you"],
          answer: "Good morning",
        },
        {
          id: "es-3-2",
          speech: { lang: "es-ES" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "How are you?",
          wordBank: ["Cómo", "estás", "tú", "bien", "adiós"],
          answer: ["Cómo", "estás"],
        },
        {
          id: "es-3-3",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Lo siento\" means?",
          options: ["Sorry", "Please", "Thanks", "Hello"],
          answer: "Sorry",
        },
      ],
    },
    {
      id: "es-basics-4",
      title: "Family",
      exercises: [
        {
          id: "es-4-1",
          speech: { lang: "es-ES" },
          type: "multipleChoice",
          prompt: "Which word means \"mother\"?",
          options: ["madre", "padre", "hermano", "hermana"],
          answer: "madre",
        },
        {
          id: "es-4-2",
          speech: { lang: "es-ES" },
          type: "multipleChoice",
          prompt: "Which word means \"father\"?",
          options: ["padre", "madre", "hijo", "hija"],
          answer: "padre",
        },
        {
          id: "es-4-3",
          speech: { lang: "es-ES" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "My sister is here",
          wordBank: ["Mi", "hermana", "está", "aquí", "hermano", "allí"],
          answer: ["Mi", "hermana", "está", "aquí"],
        },
      ],
    },
    {
      id: "es-basics-5",
      title: "Numbers",
      exercises: [
        {
          id: "es-5-1",
          speech: { lang: "es-ES" },
          type: "multipleChoice",
          prompt: "Which one means \"three\"?",
          options: ["tres", "dos", "cuatro", "uno"],
          answer: "tres",
        },
        {
          id: "es-5-2",
          speech: { lang: "es-ES" },
          type: "multipleChoice",
          prompt: "Which one means \"ten\"?",
          options: ["diez", "cinco", "siete", "nueve"],
          answer: "diez",
        },
        {
          id: "es-5-3",
          speech: { lang: "es-ES" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "I have two books",
          wordBank: ["Tengo", "dos", "libros", "tres", "uno"],
          answer: ["Tengo", "dos", "libros"],
        },
      ],
    },
  ],
  fr: [
    {
      id: "fr-basics-1",
      title: "Basics 1",
      exercises: [
        {
          id: "fr-1-1",
          speech: { lang: "fr-FR" },
          type: "multipleChoice",
          prompt: "Which word means \"the man\"?",
          options: ["l'homme", "la femme", "le garçon", "la fille"],
          answer: "l'homme",
        },
        {
          id: "fr-1-2",
          speech: { lang: "fr-FR" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "The woman drinks water",
          wordBank: ["La", "femme", "boit", "de", "l'eau", "pain"],
          answer: ["La", "femme", "boit", "de", "l'eau"],
        },
        {
          id: "fr-1-3",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Merci\" means?",
          options: ["Thank you", "Please", "Sorry", "Hello"],
          answer: "Thank you",
        },
        {
          id: "fr-1-4",
          speech: { lang: "fr-FR" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "I eat bread",
          wordBank: ["Je", "mange", "du", "pain", "tu", "manges"],
          answer: ["Je", "mange", "du", "pain"],
        },
        {
          id: "fr-1-5",
          speech: { lang: "fr-FR" },
          type: "multipleChoice",
          prompt: "Which one means \"water\"?",
          options: ["pain", "l'eau", "lait", "femme"],
          answer: "l'eau",
        },
      ],
    },
    {
      id: "fr-basics-2",
      title: "Basics 2",
      exercises: [
        {
          id: "fr-2-1",
          speech: { lang: "fr-FR" },
          type: "multipleChoice",
          prompt: "Which word means \"the boy\"?",
          options: ["le garçon", "la fille", "l'homme", "la femme"],
          answer: "le garçon",
        },
        {
          id: "fr-2-2",
          speech: { lang: "fr-FR" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "The girl eats bread",
          wordBank: ["La", "fille", "mange", "du", "pain", "l'eau"],
          answer: ["La", "fille", "mange", "du", "pain"],
        },
        {
          id: "fr-2-3",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"S'il vous plaît\" means?",
          options: ["Please", "Thank you", "Sorry", "Hello"],
          answer: "Please",
        },
        {
          id: "fr-2-4",
          speech: { lang: "fr-FR" },
          type: "multipleChoice",
          prompt: "Which one means \"milk\"?",
          options: ["lait", "eau", "pain", "garçon"],
          answer: "lait",
        },
      ],
    },
    {
      id: "fr-basics-3",
      title: "Phrases",
      exercises: [
        {
          id: "fr-3-1",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Bonjour\" means?",
          options: ["Good morning", "Good night", "Goodbye", "See you"],
          answer: "Good morning",
        },
        {
          id: "fr-3-2",
          speech: { lang: "fr-FR" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "How are you?",
          wordBank: ["Comment", "allez-vous", "bien", "au revoir"],
          answer: ["Comment", "allez-vous"],
        },
        {
          id: "fr-3-3",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Pardon\" means?",
          options: ["Sorry", "Please", "Thanks", "Hello"],
          answer: "Sorry",
        },
      ],
    },
    {
      id: "fr-basics-4",
      title: "Family",
      exercises: [
        {
          id: "fr-4-1",
          speech: { lang: "fr-FR" },
          type: "multipleChoice",
          prompt: "Which word means \"mother\"?",
          options: ["mère", "père", "frère", "sœur"],
          answer: "mère",
        },
        {
          id: "fr-4-2",
          speech: { lang: "fr-FR" },
          type: "multipleChoice",
          prompt: "Which word means \"father\"?",
          options: ["père", "mère", "fils", "fille"],
          answer: "père",
        },
        {
          id: "fr-4-3",
          speech: { lang: "fr-FR" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "My sister is here",
          wordBank: ["Ma", "sœur", "est", "ici", "frère", "là"],
          answer: ["Ma", "sœur", "est", "ici"],
        },
      ],
    },
    {
      id: "fr-basics-5",
      title: "Numbers",
      exercises: [
        {
          id: "fr-5-1",
          speech: { lang: "fr-FR" },
          type: "multipleChoice",
          prompt: "Which one means \"three\"?",
          options: ["trois", "deux", "quatre", "un"],
          answer: "trois",
        },
        {
          id: "fr-5-2",
          speech: { lang: "fr-FR" },
          type: "multipleChoice",
          prompt: "Which one means \"ten\"?",
          options: ["dix", "cinq", "sept", "neuf"],
          answer: "dix",
        },
        {
          id: "fr-5-3",
          speech: { lang: "fr-FR" },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "I have two books",
          wordBank: ["J'ai", "deux", "livres", "trois", "un"],
          answer: ["J'ai", "deux", "livres"],
        },
      ],
    },
  ],
  ja: [
    {
      id: "ja-basics-1",
      title: "Basics 1",
      exercises: [
        {
          id: "ja-1-1",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "multipleChoice",
          prompt: "Which word means \"water\"?",
          options: ["mizu", "pan", "hito", "onna"],
          answer: "mizu",
        },
        {
          id: "ja-1-2",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "I eat bread",
          wordBank: ["watashi", "wa", "pan", "o", "tabemasu", "mizu"],
          answer: ["watashi", "wa", "pan", "o", "tabemasu"],
        },
        {
          id: "ja-1-3",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Arigatou\" means?",
          options: ["Thank you", "Please", "Sorry", "Hello"],
          answer: "Thank you",
        },
        {
          id: "ja-1-4",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "multipleChoice",
          prompt: "Which word means \"the woman\"?",
          options: ["onna no hito", "otoko no hito", "kodomo", "pan"],
          answer: "onna no hito",
        },
        {
          id: "ja-1-5",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "The man drinks water",
          wordBank: ["otoko", "no", "hito", "wa", "mizu", "o", "nomimasu", "pan"],
          answer: ["otoko", "no", "hito", "wa", "mizu", "o", "nomimasu"],
        },
      ],
    },
    {
      id: "ja-basics-2",
      title: "Basics 2",
      exercises: [
        {
          id: "ja-2-1",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "multipleChoice",
          prompt: "Which word means \"boy\"?",
          options: ["otoko no ko", "onna no ko", "hito", "kodomo"],
          answer: "otoko no ko",
        },
        {
          id: "ja-2-2",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "The girl eats bread",
          wordBank: ["onna", "no", "ko", "wa", "pan", "o", "tabemasu", "mizu"],
          answer: ["onna", "no", "ko", "wa", "pan", "o", "tabemasu"],
        },
        {
          id: "ja-2-3",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Onegaishimasu\" means?",
          options: ["Please", "Thank you", "Sorry", "Hello"],
          answer: "Please",
        },
        {
          id: "ja-2-4",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "multipleChoice",
          prompt: "Which one means \"milk\"?",
          options: ["gyuunyuu", "mizu", "pan", "kodomo"],
          answer: "gyuunyuu",
        },
      ],
    },
    {
      id: "ja-basics-3",
      title: "Phrases",
      exercises: [
        {
          id: "ja-3-1",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Ohayou gozaimasu\" means?",
          options: ["Good morning", "Good night", "Goodbye", "See you"],
          answer: "Good morning",
        },
        {
          id: "ja-3-2",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "How are you?",
          wordBank: ["ogenki", "desu", "ka", "hai", "sayounara"],
          answer: ["ogenki", "desu", "ka"],
        },
        {
          id: "ja-3-3",
          speech: { lang: "en-US" },
          type: "multipleChoice",
          prompt: "\"Gomen nasai\" means?",
          options: ["Sorry", "Please", "Thanks", "Hello"],
          answer: "Sorry",
        },
      ],
    },
    {
      id: "ja-basics-4",
      title: "Family",
      exercises: [
        {
          id: "ja-4-1",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "multipleChoice",
          prompt: "Which word means \"mother\"?",
          options: ["haha", "chichi", "ani", "ane"],
          answer: "haha",
        },
        {
          id: "ja-4-2",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "multipleChoice",
          prompt: "Which word means \"father\"?",
          options: ["chichi", "haha", "musuko", "musume"],
          answer: "chichi",
        },
        {
          id: "ja-4-3",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "My sister is here",
          wordBank: ["watashi", "no", "ane", "wa", "koko", "ni", "imasu", "otouto"],
          answer: ["watashi", "no", "ane", "wa", "koko", "ni", "imasu"],
        },
      ],
    },
    {
      id: "ja-basics-5",
      title: "Numbers",
      exercises: [
        {
          id: "ja-5-1",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "multipleChoice",
          prompt: "Which one means \"three\"?",
          options: ["san", "ni", "yon", "ichi"],
          answer: "san",
        },
        {
          id: "ja-5-2",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "multipleChoice",
          prompt: "Which one means \"ten\"?",
          options: ["juu", "go", "nana", "kyuu"],
          answer: "juu",
        },
        {
          id: "ja-5-3",
          speech: { lang: "ja-JP", textByChoice: JAPANESE_SPEECH },
          type: "wordBank",
          prompt: "Translate this sentence",
          subPrompt: "I have two books",
          wordBank: ["watashi", "wa", "hon", "o", "nisatsu", "motte", "imasu", "issatsu"],
          answer: ["watashi", "wa", "hon", "o", "nisatsu", "motte", "imasu"],
        },
      ],
    },
  ],
};

export function getLessonPath(languageId: string): Lesson[] {
  return LESSON_PATHS[languageId] ?? LESSON_PATHS.es;
}
